Fix typos in docs
lavanet/docs pull request #185
Opened 2023-11-07 08:27 UTC by vuittont60

2023-11-17 20:45 UTC, KagemniKarimu requested changes
Excellent eye! 

Unfortunately, docs have undergone major changes since you made this PR! Please consider rebasing/merging in changes. Your changes on `sdk-backend.md` cause a conflict and are unlikely to be incorporated.

(Alternatively, you can allow edits by maintainers and I will reconcile the branches on your behalf!)

Thank you!

2023-11-20 03:09 UTC, vuittont60 commented
@KagemniKarimu Thanks for your review. I have rebased.

2023-12-19 20:14 UTC, KagemniKarimu approved these changes

2023-12-19 21:17 UTC, KagemniKarimu commented
Nice catch @vuittont60 💯
Thanks again for the contribution

2023-12-19 21:17 UTC, merged